/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from './openzeppelin';
export type { openzeppelin };
export type { CompLike } from './CompLike';
export type { IVOTE } from './IVOTE';
