/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorBravoInterfacesSol from './GovernorBravoInterfaces.sol';
export type { governorBravoInterfacesSol };
