/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorDelegateSol from './GovernorDelegate.sol';
export type { governorDelegateSol };
import type * as governorDelegatorSol from './GovernorDelegator.sol';
export type { governorDelegatorSol };
export type { IIpt } from './IIpt';
