/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAnchoredViewRelay,
  IAnchoredViewRelayInterface,
} from "../IAnchoredViewRelay";

const _abi = [
  {
    inputs: [],
    name: "currentValue",
    outputs: [
      {
        internalType: "uint256",
        name: "_currentValue",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAnchoredViewRelay__factory {
  static readonly abi = _abi;
  static createInterface(): IAnchoredViewRelayInterface {
    return new utils.Interface(_abi) as IAnchoredViewRelayInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAnchoredViewRelay {
    return new Contract(address, _abi, signerOrProvider) as IAnchoredViewRelay;
  }
}
