/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { IVirtualBalanceRewardPool, IVirtualBalanceRewardPoolInterface } from '../IVirtualBalanceRewardPool';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: '_ad',
        type: 'address',
      },
    ],
    name: 'earned',
    outputs: [
      {
        internalType: 'uint256',
        name: '_reward',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getReward',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_rewards',
        type: 'uint256',
      },
    ],
    name: 'queueNewRewards',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'rewardToken',
    outputs: [
      {
        internalType: 'contract IERC20',
        name: '_rewardToken',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class IVirtualBalanceRewardPool__factory {
  static readonly abi = _abi;
  static createInterface(): IVirtualBalanceRewardPoolInterface {
    return new utils.Interface(_abi) as IVirtualBalanceRewardPoolInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IVirtualBalanceRewardPool {
    return new Contract(address, _abi, signerOrProvider) as IVirtualBalanceRewardPool;
  }
}
