/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governorDelegateSol from './GovernorDelegate.sol';
export * as governorDelegatorSol from './GovernorDelegator.sol';
export { IIpt__factory } from './IIpt__factory';
