/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { IBaseRewardPool, IBaseRewardPoolInterface } from '../IBaseRewardPool';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: '_ad',
        type: 'address',
      },
    ],
    name: 'earned',
    outputs: [
      {
        internalType: 'uint256',
        name: '_reward',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_position',
        type: 'uint256',
      },
    ],
    name: 'extraRewards',
    outputs: [
      {
        internalType: 'contract IVirtualBalanceRewardPool',
        name: '_virtualReward',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'extraRewardsLength',
    outputs: [
      {
        internalType: 'uint256',
        name: '_extraRewardsLength',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_account',
        type: 'address',
      },
      {
        internalType: 'bool',
        name: '_claimExtras',
        type: 'bool',
      },
    ],
    name: 'getReward',
    outputs: [
      {
        internalType: 'bool',
        name: '_success',
        type: 'bool',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_rewards',
        type: 'uint256',
      },
    ],
    name: 'queueNewRewards',
    outputs: [
      {
        internalType: 'bool',
        name: '_success',
        type: 'bool',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'rewardToken',
    outputs: [
      {
        internalType: 'contract IERC20',
        name: '_rewardToken',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_amount',
        type: 'uint256',
      },
    ],
    name: 'stake',
    outputs: [
      {
        internalType: 'bool',
        name: '_staked',
        type: 'bool',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_for',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '_amount',
        type: 'uint256',
      },
    ],
    name: 'stakeFor',
    outputs: [
      {
        internalType: 'bool',
        name: '_staked',
        type: 'bool',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_amount',
        type: 'uint256',
      },
      {
        internalType: 'bool',
        name: '_claim',
        type: 'bool',
      },
    ],
    name: 'withdraw',
    outputs: [
      {
        internalType: 'bool',
        name: '_success',
        type: 'bool',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_amount',
        type: 'uint256',
      },
      {
        internalType: 'bool',
        name: '_claim',
        type: 'bool',
      },
    ],
    name: 'withdrawAndUnwrap',
    outputs: [
      {
        internalType: 'bool',
        name: '_success',
        type: 'bool',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;

export class IBaseRewardPool__factory {
  static readonly abi = _abi;
  static createInterface(): IBaseRewardPoolInterface {
    return new utils.Interface(_abi) as IBaseRewardPoolInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IBaseRewardPool {
    return new Contract(address, _abi, signerOrProvider) as IBaseRewardPool;
  }
}
