/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { IGovernorCharlieDelegator, IGovernorCharlieDelegatorInterface } from '../IGovernorCharlieDelegator';

const _abi = [
  {
    inputs: [],
    name: 'GovernorCharlieDelegator_InvalidImplementation',
    type: 'error',
  },
  {
    inputs: [],
    name: 'GovernorCharlieDelegator_OnlyGovernance',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: '_txHash',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'address',
        name: '_target',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_value',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'string',
        name: '_signature',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'bytes',
        name: '_data',
        type: 'bytes',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_eta',
        type: 'uint256',
      },
    ],
    name: 'CancelTransaction',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_oldEmergencyVotingPeriod',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_emergencyVotingPeriod',
        type: 'uint256',
      },
    ],
    name: 'EmergencyVotingPeriodSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: '_txHash',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'address',
        name: '_target',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_value',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'string',
        name: '_signature',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'bytes',
        name: '_data',
        type: 'bytes',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_eta',
        type: 'uint256',
      },
    ],
    name: 'ExecuteTransaction',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: '_oldAdmin',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: '_newAdmin',
        type: 'address',
      },
    ],
    name: 'NewAdmin',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_oldTimelockDelay',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_proposalTimelockDelay',
        type: 'uint256',
      },
    ],
    name: 'NewDelay',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_oldEmergencyTimelockDelay',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_emergencyTimelockDelay',
        type: 'uint256',
      },
    ],
    name: 'NewEmergencyDelay',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_oldEmergencyQuorumVotes',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_emergencyQuorumVotes',
        type: 'uint256',
      },
    ],
    name: 'NewEmergencyQuorum',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: '_oldImplementation',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: '_newImplementation',
        type: 'address',
      },
    ],
    name: 'NewImplementation',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: '_oldPendingAdmin',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: '_newPendingAdmin',
        type: 'address',
      },
    ],
    name: 'NewPendingAdmin',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_oldQuorumVotes',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_quorumVotes',
        type: 'uint256',
      },
    ],
    name: 'NewQuorum',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_oldOptimisticQuorumVotes',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_optimisticQuorumVotes',
        type: 'uint256',
      },
    ],
    name: 'OptimisticQuorumVotesSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_oldOptimisticVotingDelay',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_optimisticVotingDelay',
        type: 'uint256',
      },
    ],
    name: 'OptimisticVotingDelaySet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: '_id',
        type: 'uint256',
      },
    ],
    name: 'ProposalCanceled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: '_id',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: '_proposer',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address[]',
        name: '_targets',
        type: 'address[]',
      },
      {
        indexed: false,
        internalType: 'uint256[]',
        name: '_values',
        type: 'uint256[]',
      },
      {
        indexed: false,
        internalType: 'string[]',
        name: '_signatures',
        type: 'string[]',
      },
      {
        indexed: false,
        internalType: 'bytes[]',
        name: '_calldatas',
        type: 'bytes[]',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: '_startBlock',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_endBlock',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'string',
        name: '_description',
        type: 'string',
      },
    ],
    name: 'ProposalCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: '_id',
        type: 'uint256',
      },
    ],
    name: 'ProposalExecuted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: '_id',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_eta',
        type: 'uint256',
      },
    ],
    name: 'ProposalQueued',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_oldProposalThreshold',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_newProposalThreshold',
        type: 'uint256',
      },
    ],
    name: 'ProposalThresholdSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: '_txHash',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'address',
        name: '_target',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_value',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'string',
        name: '_signature',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'bytes',
        name: '_data',
        type: 'bytes',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_eta',
        type: 'uint256',
      },
    ],
    name: 'QueueTransaction',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: '_voter',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: '_proposalId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint8',
        name: '_support',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_votes',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'string',
        name: '_reason',
        type: 'string',
      },
    ],
    name: 'VoteCast',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_oldVotingDelay',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_newVotingDelay',
        type: 'uint256',
      },
    ],
    name: 'VotingDelaySet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_oldVotingPeriod',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_newVotingPeriod',
        type: 'uint256',
      },
    ],
    name: 'VotingPeriodSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: '_account',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_expiration',
        type: 'uint256',
      },
    ],
    name: 'WhitelistAccountExpirationSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: '_oldGuardian',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: '_newGuardian',
        type: 'address',
      },
    ],
    name: 'WhitelistGuardianSet',
    type: 'event',
  },
  {
    stateMutability: 'payable',
    type: 'fallback',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_implementation',
        type: 'address',
      },
    ],
    name: 'setImplementation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    stateMutability: 'payable',
    type: 'receive',
  },
] as const;

export class IGovernorCharlieDelegator__factory {
  static readonly abi = _abi;
  static createInterface(): IGovernorCharlieDelegatorInterface {
    return new utils.Interface(_abi) as IGovernorCharlieDelegatorInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IGovernorCharlieDelegator {
    return new Contract(address, _abi, signerOrProvider) as IGovernorCharlieDelegator;
  }
}
